#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop ev3-robolab-startup.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/ev3-robolab-startup" ] || [ -e "/etc/init/ev3-robolab-startup.conf" ]; then
	invoke-rc.d ev3-robolab-startup stop || exit $?
fi
# End automatically added section
