Document: ev3-robolab-startup
Title: Debian ev3-robolab-startup Manual
Author: <insert document author here>
Abstract: This manual describes what ev3-robolab-startup is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ev3-robolab-startup/ev3-robolab-startup.sgml.gz

Format: postscript
Files: /usr/share/doc/ev3-robolab-startup/ev3-robolab-startup.ps.gz

Format: text
Files: /usr/share/doc/ev3-robolab-startup/ev3-robolab-startup.text.gz

Format: HTML
Index: /usr/share/doc/ev3-robolab-startup/html/index.html
Files: /usr/share/doc/ev3-robolab-startup/html/*.html
